version: "3.8"
services:
  client:
    container_name: client
    build:
      context: client
      dockerfile: Dockerfile
  server:
    container_name: server
    build:
      context: contextPath
      dockerfile: Dockerfile
      target: dev
