organization: cesarclarosns
app: crunchyfans
service: media-transcode_media

frameworkVersion: "3"

plugins:
  - serverless-esbuild
  - serverless-offline

provider:
  name: aws
  runtime: nodejs20.x

functions:
  transcodeMedia:
    handler: src.index.handler
    layers:
      - !Ref FfmpegLambdaLayer
    name: ${sls.stage}-media-transcode_media
    runtime: nodejs20.x
    memorySize: 512
    provisionedConcurrency: 1
    reservedConcurrency: 1
    environment:
      S3_BUCKET_MEDIA: ${sls.stage}-chatto-media
      SQS_QUEUE_TRANSCODE_MEDIA_COMPLETE_URL:
        - Ref: queueTranscodeMediaComplete
    events:
      - sqs:
          arn:
            Fn::GetAtt:
              - queueTranscodeMediaSubmit
              - Arn
          batchSize: 1

layers:
  ffmpeg:
    path: "./layers/ffmpeg"
    name: ${sls.stage}-ffmpeg
    description: FFMPEG layer
    compatibleRuntimes:
      - nodejs20.x
      - nodejs18.x
    retain: false

resources:
  Resources:
    queueTranscodeMediaSubmit:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: ${sls.stage}-queue-media-transcode_media_submit
        RedrivePolicy:
          deadLetterTargetArn:
            Fn::GetAtt:
              - dlqueueTranscodeMediaSubmit
              - Arn
            maxReceiveCount: 1
    dlqueueTranscodeMediaSubmit:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: ${sls.stage}-dlqueue-media-transcode_media_submit

    queueTranscodeMediaComplete:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: ${sls.stage}-queue-media-transcode_media_complete
        RedrivePolicy:
          deadLetterTargetArn:
            Fn::GetAtt:
              - dlqueueTranscodeMediaComplete
              - Arn
            maxReceiveCount: 1
    dlqueueTranscodeMediaComplete:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: ${sls.stage}-dlqueue-media-transcode_media_complete
