org: cesarclarosns
app: crunchyfans
service: media-resources

frameworkVersion: "3"

plugins:
  - serverless-s3-local
  # - serverless-offline-sqs
  - serverless-offline

provider:
  name: aws
  region: us-east-1
  runtime: nodejs20.x

custom:
  s3:
    port: 4569
    directory: /tmp
    cors: ./s3-cors.xml
    allowMismatchedSignatures: true
    silent: true

  serverless-offline-sqs:
    autoCreate: true # create queue if not exists
    apiVersion: "2012-11-05"
    endpoint: http://0.0.0.0:9324
    region: us-east-1
    accessKeyId: root
    secretAccessKey: root
    skipCacheInvalidation: false

resources:
  Resources:
    bucketMedia:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: crunchyfans.media
        CorsConfiguration:
          CorsRules:
            - AllowedMethods:
                - "GET"
                - "HEAD"
                - "POST"
                - "PUT"
              AllowedOrigins:
                - "*"
              AllowedHeaders:
                - "*"
              ExposedHeaders:
                - ETag

    bucketMediaProcessing:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: crunchyfans.transcoder
        CorsConfiguration:
          CorsRules:
            - AllowedMethods:
                - "GET"
                - "HEAD"
                - "POST"
                - "PUT"
              AllowedOrigins:
                - "*"
              AllowedHeaders:
                - "*"
              ExposedHeaders:
                - ETag
